# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ergonamesapi:
    image: ergonamesapi
    build:
      context: .
      dockerfile: src/ErgoNames.Api/Dockerfile
    ports:
      - 5000:5000
